name: home-robot
channels:
  - conda-forge
  - nvidia
  - defaults
  - aihabitat
  - pyg
  - pytorch
  - pytorch3d
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - _x86_64-microarch-level=4=3_x86_64_v4
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.12.15=py39heb7d2ae_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - ampl-asl=1.0.0=h5888daf_2
  - aom=3.9.1=hac33072_0
  - assimp=5.4.3=hecf2907_1
  - async-timeout=5.0.1=pyhd8ed1ab_1
  - attrs=25.3.0=pyh71513ae_0
  - blas=2.121=mkl
  - blas-devel=3.9.0=21_linux64_mkl
  - brotli-python=1.1.0=py39hf88036b_3
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cairo=1.18.4=h3394656_0
  - casadi=3.7.0=py39hfa75d24_4
  - certifi=2025.8.3=pyhd8ed1ab_0
  - cffi=1.17.1=py39h15c3d72_0
  - charset-normalizer=3.4.3=pyhd8ed1ab_0
  - cli11=2.6.0=h54a6638_0
  - cmake=4.2.0=hc85cc9f_0
  - coal=3.0.1=hf3d152e_3
  - coal-python=3.0.1=py39h6bc7560_3
  - colorama=0.4.6=pyhd8ed1ab_1
  - console_bridge=1.0.2=h924138e_1
  - cuda-cudart=11.7.99=0
  - cuda-cupti=11.7.101=0
  - cuda-libraries=11.7.1=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-runtime=11.7.1=0
  - cuda-version=13.0=3
  - cycler=0.12.1=pyhd8ed1ab_1
  - dataclasses=0.8=pyhc8e2a94_3
  - dav1d=1.2.1=hd590300_0
  - eigen=3.4.0=h171cf75_1
  - elfutils=0.192=hebdcf93_2
  - exa=0.10.1=habb4d0f_0
  - ffmpeg=7.1.0=gpl_he2fd91e_701
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - freetype=2.14.1=ha770c72_0
  - fribidi=1.0.16=hb03c661_0
  - frozenlist=1.7.0=py39h53edacf_0
  - fsspec=2025.7.0=pyhd8ed1ab_0
  - fvcore=0.1.5.post20221221=pyhd8ed1ab_0
  - fzf=0.67.0=h6138981_0
  - gdbm=1.18=h0a1914f_2
  - gettext=0.25.1=h3f43e3d_1
  - gettext-tools=0.25.1=h3f43e3d_1
  - gitdb=4.0.12=pyhd8ed1ab_0
  - gitpython=3.1.45=pyhff2d567_0
  - gmp=6.3.0=hac33072_2
  - gnutls=3.8.7=h91970d1_1
  - graphite2=1.3.14=hecca717_2
  - h2=4.2.0=pyhd8ed1ab_0
  - habitat-sim-mutex=1.0=headless_nobullet
  - harfbuzz=12.2.0=h15599e2_0
  - headless=2.0=0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_1
  - iopath=0.1.10=pyhd8ed1ab_0
  - ipopt=3.14.19=h6c08d29_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.1=pyhd8ed1ab_0
  - jpeg=9e=h0b41bf4_3
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.7=py39h74842e3_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.17=heab6991_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_104
  - lerc=4.0.0=h0aef613_1
  - libabseil=20240722.0=cxx17_hbbce691_4
  - libarchive=3.8.1=gpl_h98cc613_100
  - libasprintf=0.25.1=h3f43e3d_1
  - libasprintf-devel=0.25.1=h3f43e3d_1
  - libass=0.17.3=hba53ac1_1
  - libblas=3.9.0=21_linux64_mkl
  - libblasfeo=0.1.4.2=had105d5_300
  - libboost=1.88.0=hed09d94_1
  - libboost-devel=1.88.0=hfcd1e18_1
  - libboost-headers=1.88.0=ha770c72_1
  - libboost-python=1.88.0=py39h040329f_1
  - libboost-python-devel=1.88.0=py39hf0d4527_1
  - libcblas=3.9.0=21_linux64_mkl
  - libcoal=3.0.1=h969b668_3
  - libcublas=11.10.3.66=0
  - libcufft=10.7.2.124=h4fbf590_0
  - libcufile=1.15.1.6=h2e68323_0
  - libcurand=10.4.0.35=h50d9014_0
  - libcurl=8.17.0=h4e3cde8_0
  - libcusolver=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libdeflate=1.22=hb9d3cd8_0
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libexpat=2.7.3=hecca717_0
  - libfatrop=0.0.4=h5888daf_1
  - libffi=3.5.2=h9ec8514_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=he0feb66_14
  - libgcc-ng=15.2.0=h69a702a_14
  - libgettextpo=0.25.1=h3f43e3d_1
  - libgettextpo-devel=0.25.1=h3f43e3d_1
  - libgfortran=15.2.0=h69a702a_14
  - libgfortran-ng=15.2.0=h69a702a_14
  - libgfortran5=15.2.0=h68bc16d_14
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.86.2=h6548e54_1
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgz-cmake3=3.5.5=h54a6638_0
  - libgz-cmake4=4.2.0=h54a6638_1
  - libgz-math7=7.5.2=h54a6638_2
  - libgz-tools=2.0.3=h54a6638_1
  - libgz-utils2=2.2.1=h54a6638_1
  - libhwloc=2.12.1=default_h3d81e11_1000
  - libiconv=1.18=h3b78370_2
  - libidn2=2.1.1=h14c3975_0
  - liblapack=3.9.0=21_linux64_mkl
  - liblapacke=3.9.0=21_linux64_mkl
  - libllvm14=14.0.6=hcd5def8_4
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libmicrohttpd=1.0.1=hbc5bc17_1
  - libnghttp2=1.67.0=had1ee68_0
  - libnpp=11.7.4.75=0
  - libnsl=2.0.1=hb9d3cd8_1
  - libnvjpeg=11.8.0.2=0
  - libopenvino=2024.4.0=hac27bb2_2
  - libopenvino-auto-batch-plugin=2024.4.0=h4d9b6c2_2
  - libopenvino-auto-plugin=2024.4.0=h4d9b6c2_2
  - libopenvino-hetero-plugin=2024.4.0=h3f63f65_2
  - libopenvino-intel-cpu-plugin=2024.4.0=hac27bb2_2
  - libopenvino-intel-gpu-plugin=2024.4.0=hac27bb2_2
  - libopenvino-intel-npu-plugin=2024.4.0=hac27bb2_2
  - libopenvino-ir-frontend=2024.4.0=h3f63f65_2
  - libopenvino-onnx-frontend=2024.4.0=h5c8f2c3_2
  - libopenvino-paddle-frontend=2024.4.0=h5c8f2c3_2
  - libopenvino-pytorch-frontend=2024.4.0=h5888daf_2
  - libopenvino-tensorflow-frontend=2024.4.0=h6481b9d_2
  - libopenvino-tensorflow-lite-frontend=2024.4.0=h5888daf_2
  - libopus=1.5.2=hd0c01bc_0
  - libosqp=1.0.0=np2py312h1a77e3e_2
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.51=h421ea60_0
  - libprotobuf=5.28.2=h5b01275_0
  - libqdldl=0.1.8=h3f2d84a_1
  - libscotch=7.0.10=int32_h8512f2c_2
  - libsdformat14=14.8.0=py310hde68ca4_2
  - libspral=2025.05.20=hfabd9d1_1
  - libsqlite=3.51.1=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h934c35e_14
  - libstdcxx-ng=15.2.0=hdf11a46_14
  - libtasn1=4.20.0=hb03c661_1
  - libtiff=4.7.1=h029b1ac_0
  - libunistring=1.3=hb25bd0a_0
  - libuuid=2.41.2=he9a06e4_0
  - libuv=1.51.0=hb03c661_1
  - libva=2.22.0=h4f16b4b_2
  - libvpx=1.14.1=hac33072_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.9=h04c0eec_0
  - libzlib=1.3.1=hb9d3cd8_2
  - llvm-openmp=21.1.6=h4922eb0_0
  - lz4-c=1.10.0=h5888daf_1
  - lzo=2.10=h280c20c_1002
  - markupsafe=3.0.2=py39h9399b63_1
  - matplotlib-base=3.3.2=py39h98787fa_1
  - metis=5.1.0=hd0bcaf9_1007
  - mkl-devel=2024.0.0=ha770c72_49657
  - mkl-include=2024.0.0=ha957f24_49657
  - multidict=6.6.3=py39h9399b63_0
  - mumps-include=5.8.1=h1795ed4_4
  - mumps-seq=5.8.1=h4374b6a_4
  - ncurses=6.5=h2d0b736_3
  - nettle=3.10.2=hc3b2e76_0
  - numba=0.60.0=py39h0320e7d_0
  - ocl-icd=2.3.3=hb9d3cd8_0
  - octomap=1.10.0=h84d6215_0
  - opencl-headers=2025.06.13=h5888daf_0
  - openh264=2.4.1=h59595ed_0
  - openjpeg=2.5.4=h55fea9a_0
  - openssl=3.6.0=h26f9b46_0
  - pcre2=10.47=haa7fec5_0
  - pinocchio=3.7.0=py39h98ca88a_1
  - pip=25.2=pyh8b19718_0
  - pixman=0.46.4=h54a6638_1
  - portalocker=3.2.0=py39hf3d152e_0
  - propcache=0.3.1=py39h9399b63_0
  - psutil=7.0.0=py39h8cd3c5a_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pugixml=1.14=h59595ed_0
  - pybind11=3.0.1=pyh7a1b43c_0
  - pybind11-global=3.0.1=pyhc7ab6ef_0
  - pycparser=2.22=pyh29332c3_1
  - pyg=2.5.2=py39_torch_1.13.0_cu117
  - pyparsing=3.2.3=pyhe01879c_2
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.9.23=hc30ae73_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.9=8_cp39
  - pytorch-cluster=1.6.1=py39_torch_1.13.0_cu117
  - pytorch-cuda=11.7=h778d358_5
  - pytorch-mutex=1.0=cuda
  - pytorch-scatter=2.1.1=py39_torch_1.13.0_cu117
  - pytorch3d=0.7.5=py39_cu117_pyt1131
  - pyyaml=6.0.2=py39h9399b63_2
  - qhull=2020.2=h434a139_5
  - qhull-static=2020.2=h434a139_5
  - quaternion=2023.0.4=py39hf15bc26_0
  - readline=8.2=h8c095d6_2
  - requests=2.32.5=pyhd8ed1ab_0
  - rhash=1.4.6=hb9d3cd8_1
  - ruby=3.4.7=h498564d_1
  - scikit-learn=1.6.1=py39h4b7350c_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - smmap=3.0.5=pyh44b312d_0
  - snappy=1.2.2=h03e3b7b_1
  - sophus=1!1.24.6=he02047a_2
  - svt-av1=2.2.1=h5888daf_0
  - tabulate=0.9.0=pyhd8ed1ab_2
  - termcolor=3.1.0=pyhd8ed1ab_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tinyxml2=11.0.0=h3f2d84a_0
  - tk=8.6.13=noxft_ha0e22de_103
  - torchaudio=0.13.1=py39_cu117
  - torchvision=0.14.1=py39_cu117
  - tornado=6.5.2=py39hd399759_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - typing-extensions=4.14.1=h4440ef1_0
  - typing_extensions=4.14.1=pyhe01879c_0
  - urdfdom=4.0.1=hae71d53_3
  - urdfdom_headers=1.1.2=h84d6215_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wayland=1.24.0=hd6090a7_1
  - wayland-protocols=1.46=hd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxinerama=1.1.5=h5888daf_1
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - yacs=0.1.8=pyh29332c3_2
  - yaml=0.2.5=h280c20c_3
  - yarl=1.20.1=py39h9399b63_0
  - zlib=1.3.1=hb9d3cd8_2
  - zstandard=0.23.0=py39hd399759_3
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - absl-py==2.3.1
      - accelerate==1.10.1
      - addict==2.4.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.12.0
      - asttokens==3.0.1
      - atomicwrites==1.4.1
      - blinker==1.9.0
      - braceexpand==0.1.7
      - cachetools==6.2.2
      - catkin-pkg==1.1.0
      - cfgv==3.4.0
      - click==8.1.8
      - cloudpickle==3.1.2
      - cmeel==0.57.3
      - cmeel-assimp==5.4.3.1
      - cmeel-boost==1.82.0
      - cmeel-console-bridge==1.0.2.3
      - cmeel-octomap==1.10.0
      - cmeel-tinyxml==2.6.2.3
      - cmeel-urdfdom==3.1.1.1
      - cmeel-zlib==1.3.1
      - comm==0.2.3
      - configargparse==1.7.1
      - contourpy==1.3.0
      - dash==3.3.0
      - debugpy==1.8.17
      - decorator==5.2.1
      - diffusers==0.35.2
      - distlib==0.4.0
      - distro==1.9.0
      - docutils==0.22.3
      - eigenpy==3.1.3
      - empy==4.2
      - evdev==1.9.2
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - farama-notifications==0.0.4
      - faster-fifo==1.5.2
      - fastjsonschema==2.21.2
      - filelock==3.19.1
      - flask==3.1.2
      - fonttools==4.60.1
      - frozendict==2.4.7
      - ftfy==6.3.1
      - genpy==2022.1
      - google-auth==2.43.0
      - google-auth-oauthlib==0.4.6
      - grpcio==1.76.0
      - gym==0.23.0
      - gym-notices==0.1.0
      - gymnasium==1.1.1
      - h11==0.16.0
      - h5py==3.11.0
      - habitat-baselines==0.2.5
      - habitat-lab==0.2.5
      - habitat-sim==0.3.3
      - hf-xet==1.2.0
      - home-robot==0.1.0
      - home-robot-hw==1.0.0
      - hpp-fcl==2.3.6
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.1.6
      - hydra-core==1.3.2
      - identify==2.6.15
      - ifcfg==0.24
      - imageio==2.37.2
      - imageio-ffmpeg==0.6.0
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - iniconfig==2.1.0
      - intel-cmplr-lib-ur==2024.2.1
      - intel-openmp==2024.2.1
      - ipykernel==6.31.0
      - ipython==8.18.1
      - ipywidgets==8.1.8
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - jupyterlab-widgets==3.0.16
      - lazy-loader==0.4
      - llvmlite==0.43.0
      - lmdb==1.7.5
      - loguru==0.7.3
      - markdown==3.9
      - markdown-it-py==3.0.0
      - matplotlib==3.9.4
      - matplotlib-inline==0.2.1
      - mdurl==0.1.2
      - mkl==2024.0.0
      - moviepy==2.2.1
      - mpmath==1.3.0
      - msgpack==1.1.2
      - mss==10.1.0
      - narwhals==2.12.0
      - natsort==8.4.0
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - nodeenv==1.9.1
      - numpy==1.23.5
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - oauthlib==3.3.1
      - objectio==0.2.29
      - omegaconf==2.3.0
      - open3d==0.19.0
      - openai-clip==1.0.1
      - opencv-python==4.11.0.86
      - packaging==25.0
      - pandas==2.3.3
      - parso==0.8.5
      - pexpect==4.9.0
      - pillow==10.3.0
      - pin==2.6.20
      - platformdirs==4.4.0
      - plotly==6.5.0
      - pluggy==1.6.0
      - pre-commit==4.3.0
      - proglog==0.1.12
      - prompt-toolkit==3.0.52
      - protobuf==3.20.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pybullet==3.2.7
      - pycocotools==2.0.10
      - pygame==2.0.1
      - pygifsicle==1.1.0
      - pygments==2.19.2
      - pynput==1.8.1
      - pyquaternion==0.9.9
      - pytest==8.4.2
      - python-dotenv==1.2.1
      - python-xlib==0.33
      - pytools==2024.1.14
      - pytz==2025.2
      - pyzmq==27.1.0
      - referencing==0.36.2
      - regex==2025.11.3
      - requests-oauthlib==2.0.0
      - retrying==1.4.2
      - rich==14.2.0
      - rosnumpy==0.0.6.2
      - rospkg==1.6.0
      - rpds-py==0.27.1
      - rsa==4.9.1
      - safetensors==0.7.0
      - scikit-fmm==2025.1.29
      - scikit-image==0.24.0
      - scipy==1.13.0
      - shellingham==1.5.4
      - simplejson==3.20.2
      - sophuspy==1.2.0
      - stack-data==0.6.3
      - sympy==1.14.0
      - tbb==2021.13.1
      - tensorboard==2.8.0
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tifffile==2024.8.30
      - timm==1.0.22
      - tomli==2.3.0
      - torch==2.8.0
      - traitlets==5.14.3
      - trimesh==3.23.5
      - triton==3.4.0
      - typer==0.20.0
      - typer-slim==0.20.0
      - tzdata==2025.2
      - virtualenv==20.35.4
      - wcwidth==0.2.14
      - webdataset==0.1.40
      - werkzeug==3.1.4
      - widgetsnbextension==4.0.15
      - zipp==3.23.0
prefix: /home/jinyoonok/miniconda3/envs/home-robot
